### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by LinLL** [AndreyErmilov/pytest-mock-server#1]
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))
Raise exception at running example.But it will not raise if sleep some time.

**Comment by AndreyErmilov** [comment]
Hi @LinLL!
Sorry for late response. 
I'm going to fix it next week.

**Comment by AndreyErmilov** [comment]
@LinLL Please write me what is your operating system and version of python
