### ISSUE TITLE
Configure the port on which the mock server listens

### ISSUE THREAD

**Issue by danbaragan** [AndreyErmilov/pytest-mock-server#3]
This a really neat mock server for pytest.
Kudos for it's simplicity.

I found though that it is a little bit of a hazard to base tests on it because of the port.
It opens a default flask on 5000 and this is not configurable in any way.
This is a liability as other services might be running on that very common port.
I, for instance, start a docker-compose suite, with my dev flask app on 5000, and exec in the python machine that runs the flask app in order run also run the tests. All the tests fail with 404 because the requests go to the main flask app that does not know about the routes.

I could move the main flask app - but it is weird to switch ports because of the test suite.
This might not be an option on other environments and it will yield unpredictable behaviour if forgotten.

It would be really nice if the port mock server starts on could be configured from the environment or otherwise.

Thanks!

**Comment by AndreyErmilov** [comment]
Hey @danbaragan! 
Sorry for my delay! I agree it's a good idea to add server config. I'm going to add a config in the next one or two weeks.

**Comment by intsynko** [comment]
I have a solution of this problem, can you grant me a rights to create new branches and pull requests?

P.S. @AndreyErmilov, I have created [pull request](https://github.com/AndreyErmilov/pytest-mock-server/pull/4)
